//go:build !ignore_autogenerated

/*
Copyright 2025 Huawei Cloud.

Licensed under the MIT No Attribution (MIT-0) License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/cluster-api/api/core/v1beta2"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddonSpec) DeepCopyInto(out *AddonSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddonSpec.
func (in *AddonSpec) DeepCopy() *AddonSpec {
	if in == nil {
		return nil
	}
	out := new(AddonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingSpec) DeepCopyInto(out *BillingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingSpec.
func (in *BillingSpec) DeepCopy() *BillingSpec {
	if in == nil {
		return nil
	}
	out := new(BillingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCEManagedControlPlane) DeepCopyInto(out *CCEManagedControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCEManagedControlPlane.
func (in *CCEManagedControlPlane) DeepCopy() *CCEManagedControlPlane {
	if in == nil {
		return nil
	}
	out := new(CCEManagedControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CCEManagedControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCEManagedControlPlaneList) DeepCopyInto(out *CCEManagedControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CCEManagedControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCEManagedControlPlaneList.
func (in *CCEManagedControlPlaneList) DeepCopy() *CCEManagedControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(CCEManagedControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CCEManagedControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCEManagedControlPlaneSpec) DeepCopyInto(out *CCEManagedControlPlaneSpec) {
	*out = *in
	in.ContainerNetwork.DeepCopyInto(&out.ContainerNetwork)
	out.ServiceNetwork = in.ServiceNetwork
	if in.CustomSan != nil {
		in, out := &in.CustomSan, &out.CustomSan
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.EndpointAccess = in.EndpointAccess
	if in.IdentityRef != nil {
		in, out := &in.IdentityRef, &out.IdentityRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	out.Billing = in.Billing
	if in.Addons != nil {
		in, out := &in.Addons, &out.Addons
		*out = make([]AddonSpec, len(*in))
		copy(*out, *in)
	}
	if in.PodIdentityAssociations != nil {
		in, out := &in.PodIdentityAssociations, &out.PodIdentityAssociations
		*out = make([]PodIdentityAssociationSpec, len(*in))
		copy(*out, *in)
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(ControlPlaneLoggingSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCEManagedControlPlaneSpec.
func (in *CCEManagedControlPlaneSpec) DeepCopy() *CCEManagedControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(CCEManagedControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCEManagedControlPlaneStatus) DeepCopyInto(out *CCEManagedControlPlaneStatus) {
	*out = *in
	if in.ControlPlaneEndpoint != nil {
		in, out := &in.ControlPlaneEndpoint, &out.ControlPlaneEndpoint
		*out = new(v1beta2.APIEndpoint)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCEManagedControlPlaneStatus.
func (in *CCEManagedControlPlaneStatus) DeepCopy() *CCEManagedControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(CCEManagedControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCEManagedControlPlaneTemplate) DeepCopyInto(out *CCEManagedControlPlaneTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCEManagedControlPlaneTemplate.
func (in *CCEManagedControlPlaneTemplate) DeepCopy() *CCEManagedControlPlaneTemplate {
	if in == nil {
		return nil
	}
	out := new(CCEManagedControlPlaneTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CCEManagedControlPlaneTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCEManagedControlPlaneTemplateList) DeepCopyInto(out *CCEManagedControlPlaneTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CCEManagedControlPlaneTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCEManagedControlPlaneTemplateList.
func (in *CCEManagedControlPlaneTemplateList) DeepCopy() *CCEManagedControlPlaneTemplateList {
	if in == nil {
		return nil
	}
	out := new(CCEManagedControlPlaneTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CCEManagedControlPlaneTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCEManagedControlPlaneTemplateResource) DeepCopyInto(out *CCEManagedControlPlaneTemplateResource) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCEManagedControlPlaneTemplateResource.
func (in *CCEManagedControlPlaneTemplateResource) DeepCopy() *CCEManagedControlPlaneTemplateResource {
	if in == nil {
		return nil
	}
	out := new(CCEManagedControlPlaneTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCEManagedControlPlaneTemplateSpec) DeepCopyInto(out *CCEManagedControlPlaneTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCEManagedControlPlaneTemplateSpec.
func (in *CCEManagedControlPlaneTemplateSpec) DeepCopy() *CCEManagedControlPlaneTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(CCEManagedControlPlaneTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerNetworkSpec) DeepCopyInto(out *ContainerNetworkSpec) {
	*out = *in
	if in.ENISubnets != nil {
		in, out := &in.ENISubnets, &out.ENISubnets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerNetworkSpec.
func (in *ContainerNetworkSpec) DeepCopy() *ContainerNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(ContainerNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneLogSpec) DeepCopyInto(out *ControlPlaneLogSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneLogSpec.
func (in *ControlPlaneLogSpec) DeepCopy() *ControlPlaneLogSpec {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneLogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneLoggingSpec) DeepCopyInto(out *ControlPlaneLoggingSpec) {
	*out = *in
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = make([]ControlPlaneLogSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneLoggingSpec.
func (in *ControlPlaneLoggingSpec) DeepCopy() *ControlPlaneLoggingSpec {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneLoggingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointAccessSpec) DeepCopyInto(out *EndpointAccessSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointAccessSpec.
func (in *EndpointAccessSpec) DeepCopy() *EndpointAccessSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointAccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodIdentityAssociationSpec) DeepCopyInto(out *PodIdentityAssociationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodIdentityAssociationSpec.
func (in *PodIdentityAssociationSpec) DeepCopy() *PodIdentityAssociationSpec {
	if in == nil {
		return nil
	}
	out := new(PodIdentityAssociationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceNetworkSpec) DeepCopyInto(out *ServiceNetworkSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceNetworkSpec.
func (in *ServiceNetworkSpec) DeepCopy() *ServiceNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceNetworkSpec)
	in.DeepCopyInto(out)
	return out
}
