//go:build !ignore_autogenerated

/*
Copyright 2025 Huawei Cloud.

Licensed under the MIT No Attribution (MIT-0) License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingSpec) DeepCopyInto(out *BillingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingSpec.
func (in *BillingSpec) DeepCopy() *BillingSpec {
	if in == nil {
		return nil
	}
	out := new(BillingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCEManagedControlPlane) DeepCopyInto(out *CCEManagedControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCEManagedControlPlane.
func (in *CCEManagedControlPlane) DeepCopy() *CCEManagedControlPlane {
	if in == nil {
		return nil
	}
	out := new(CCEManagedControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CCEManagedControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCEManagedControlPlaneList) DeepCopyInto(out *CCEManagedControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CCEManagedControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCEManagedControlPlaneList.
func (in *CCEManagedControlPlaneList) DeepCopy() *CCEManagedControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(CCEManagedControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CCEManagedControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCEManagedControlPlaneSpec) DeepCopyInto(out *CCEManagedControlPlaneSpec) {
	*out = *in
	in.ContainerNetwork.DeepCopyInto(&out.ContainerNetwork)
	out.ServiceNetwork = in.ServiceNetwork
	if in.CustomSan != nil {
		in, out := &in.CustomSan, &out.CustomSan
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.EndpointAccess = in.EndpointAccess
	out.Billing = in.Billing
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCEManagedControlPlaneSpec.
func (in *CCEManagedControlPlaneSpec) DeepCopy() *CCEManagedControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(CCEManagedControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCEManagedControlPlaneStatus) DeepCopyInto(out *CCEManagedControlPlaneStatus) {
	*out = *in
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCEManagedControlPlaneStatus.
func (in *CCEManagedControlPlaneStatus) DeepCopy() *CCEManagedControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(CCEManagedControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerNetworkSpec) DeepCopyInto(out *ContainerNetworkSpec) {
	*out = *in
	if in.ENISubnets != nil {
		in, out := &in.ENISubnets, &out.ENISubnets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerNetworkSpec.
func (in *ContainerNetworkSpec) DeepCopy() *ContainerNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(ContainerNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointAccessSpec) DeepCopyInto(out *EndpointAccessSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointAccessSpec.
func (in *EndpointAccessSpec) DeepCopy() *EndpointAccessSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointAccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceNetworkSpec) DeepCopyInto(out *ServiceNetworkSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceNetworkSpec.
func (in *ServiceNetworkSpec) DeepCopy() *ServiceNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceNetworkSpec)
	in.DeepCopyInto(out)
	return out
}
